default : serveur client 

serveur : serveur.c
	gcc -g -Wall serveur.c -o serveur_/serveur

client : client.c
	gcc -g -Wall client.c -o client_/client


runserveur :
	serveur_/serveur

runclient :
	client_/client
